import '../interfaces/restaurant.dart';
import 'package:cloud_firestore/cloud_firestore.dart';

List<Map<String, dynamic>> _restaurantData = [
  {
    'chefName': 'Massimo Bottura',
    'mainImage': 'massimo_bottura_osteria_francescana.jpg',
    'restaurantName': 'Osteria Francescana',
    'netflixShowName': 'Chef Table',
    'volume': 1,
    'chapter': 1,
    'city': 'Modena',
    'lat': 44.64506,
    'lng': 10.92156,
    'images': [],
    'address': 'Via Stella, 22, 41121 Modena MO, Italy',
    'country': 'Italy',
    'description':
        "By blending Italian tradition and artful modernity, chef Massimo Bottura's Osteria Francescana has been ranked the third best restaurant in the world",
    'webPage': 'https://osteriafrancescana.it/',
    'reservationsMail': '',
    'contactPhone': '',
    'reservations': '',
    'isFavorited': true,
  },
  {
    'chefName': 'Dan Barber',
    'mainImage': 'blue_hill_farm.jpeg',
    'restaurantName': 'Blue Hill, Stone B.',
    'netflixShowName': 'Chef Table',
    'volume': 1,
    'chapter': 2,
    'city': 'New York',
    'country': 'United States',
    'lat': 41.19109,
    'lng': -73.82856,
    'images': [],
    'address': '630 Bedford Rd, Tarrytown, NY 10591',
    'description':
        "Celebrated chef, dedicated farmer and food industry revolutionary Dan Barber is leading a fight to change the way we think about, and grow, our food",
    'webPage': 'https://www.bluehillfarm.com/',
    'reservationsMail': 'reservationsnyc@bluehillfarm.com',
    'contactPhone': '(914) 366 9600',
    'reservations': 'https://www.exploretock.com/bluehillatstonebarns/search',
    'isFavorited': false,
  },
  {
    'chefName': 'Francis Mallmann',
    'mainImage': 'francis_mallman.webp',
    'restaurantName': '1884 Francis M.',
    'netflixShowName': 'Chef Table',
    'volume': 1,
    'chapter': 3,
    'city': 'Mendoza',
    'country': 'Argentina',
    'lat': -32.90276,
    'lng': -68.84218,
    'images': [],
    'address': 'Belgrano 1188, Godoy Cruz, Mendoza, Argentina',
    'description':
        "South Americas best-known chef, Francis Mallmann, owns and runs this restaurant. He is known for his open-fire cooking and his use of local ingredients ",
    'webPage': '',
    'reservationsMail': '',
    'contactPhone': '',
    'reservations': '',
    'isFavorited': false,
  },
  {
    'chefName': 'Niki Nakayama',
    'mainImage': 'n_naka.jpg',
    'restaurantName': 'N/naka',
    'netflixShowName': 'Chef Table',
    'volume': 1,
    'chapter': 4,
    'city': 'Los Angeles',
    'country': 'U.S.A',
    'lat': 34.02536,
    'lng': -118.41213,
    'images': [],
    'address': '3455 Overland Ave, Los Angeles, CA 90034, Estados Unidos',
    'description':
        "In her award-winning Los Angeles restaurant, N/Naka, chef Niki Nakayama brings equal parts creativity, passion and expertise to her kaiseki cuisine.",
    'webPage': '',
    'reservationsMail': '',
    'contactPhone': '(+1) 310 836 6252',
    'reservations': '',
    'isFavorited': false,
  },
  {
    'chefName': 'Ben Shewry',
    'mainImage': 'attica.jpeg',
    'restaurantName': 'Attica',
    'netflixShowName': 'Chef Table',
    'volume': 1,
    'chapter': 5,
    'city': 'New Zeland',
    'country': 'Australia',
    'lat': -37.87689,
    'lng': 144.99733,
    'images': [],
    'address': '74 Glen Eira Rd, Ripponlea VIC 3185, Australia',
    'description':
        "New Zeland chef Ben Shewry's string connection with nature and dedication to finding new tastes have made his striking restaurant Attica a temple to the art of cooking",
    'webPage': '',
    'reservationsMail': '',
    'contactPhone': '',
    'reservations': '',
    'isFavorited': false,
  },
  {
    'chefName': 'Grant Achatz',
    'mainImage': 'alinea.jpeg',
    'restaurantName': 'Alinea',
    'netflixShowName': 'Chef Table',
    'volume': 2,
    'chapter': 1,
    'city': 'Chicago',
    'country': 'U.S.A.',
    'lat': 41.91344,
    'lng': -87.64805,
    'images': [],
    'address': '1723 N Halsted St, Chicago, IL 60614, Estados Unidos',
    'description':
        "Superstar American chef Grant Achatz has been at the forefront of the molecular gastronomy movement since the 1990s. He wants to vow diners with mistery, emotion and magic just as much as he does with flavor and beauty",
    'webPage': '',
    'reservationsMail': '',
    'contactPhone': '',
    'reservations': '',
    'isFavorited': false,
  },
  {
    'chefName': 'Alex Atala',
    'mainImage': 'dom_alex_atala.jpeg',
    'restaurantName': 'D.O.M.',
    'netflixShowName': 'Chef Table',
    'volume': 2,
    'chapter': 2,
    'city': 'São Paulo',
    'country': 'Brasil',
    'lat': -23.56628,
    'lng': -46.66745,
    'images': [],
    'address': 'R. Barão de Capanema, 549 - Jardins, São Paulo - SP, 01411-011',
    'description':
        "Brazilian chef Alex Atala is a pioneer of the country's new wave of chefs who are redefining the country's cuisine. He relies on his wild spirit and love for the Amazon to show diners how an open mind pays off deliciousness",
    'webPage': '',
    'reservationsMail': '',
    'contactPhone': '',
    'reservations': '',
    'isFavorited': false,
  },
  {
    'chefName': 'Dominique Crenn',
    'mainImage': 'atelier_crenn.jpeg',
    'restaurantName': 'Atelier Crenn',
    'netflixShowName': 'Chef Table',
    'volume': 2,
    'chapter': 3,
    'city': 'San Francisco',
    'country': 'U.S.A.',
    'lat': 37.79835,
    'lng': -122.43589,
    'images': [],
    'address': '3127 Fillmore St, San Francisco, CA 94123, United States',
    'description':
        "French-born Dominique Creen's love for life, family and personal connection helped her become the first two-Michelin star chef in America. Now it's a three-Michelin star restaurant with modern, innovative French cousine",
    'webPage': '',
    'reservationsMail': '',
    'contactPhone': '',
    'reservations': '',
    'isFavorited': false,
  },
  {
    'chefName': 'Enrique Olvera',
    'mainImage': 'pujol.jpg',
    'restaurantName': 'Pujol',
    'netflixShowName': 'Chef Table',
    'volume': 2,
    'chapter': 4,
    'city': 'D.F',
    'country': 'Mexico',
    'lat': 19.43558,
    'lng': -99.19480,
    'images': [],
    'address':
        'Tennyson 133, Polanco, Polanco IV Secc, Miguel Hidalgo, 11550 Ciudad de México, CDMX, México',
    'description':
        "Chef Enrique Olvera transforms Mexico's most savory street foods and traditional ingredients into award-dinning dishes at his Mexico City restaurant",
    'webPage': '',
    'reservationsMail': '',
    'contactPhone': '',
    'reservations': '',
    'isFavorited': false,
  },
  {
    'chefName': 'Ana Rös',
    'mainImage': 'hisa_franco_restaurant.jpeg',
    'restaurantName': 'Hiša Franko',
    'netflixShowName': 'Chef Table',
    'volume': 2,
    'chapter': 5,
    'city': 'Kobarid',
    'country': 'Eslovenia',
    'lat': 46.24724,
    'lng': 13.53775,
    'images': [],
    'address': 'Staro selo 1, 5222 Kobarid, Eslovenia',
    'description':
        "Self-taught Slovenian chef Ana Rös uses ingredients from her remote surroundings to create inspired and surprising dishes. ",
    'webPage': '',
    'reservationsMail': '',
    'contactPhone': '(+386) 5 389 41 20',
    'reservations': '',
    'isFavorited': false,
  },
  {
    'chefName': 'Gaggan Anand',
    'mainImage': 'gaggan_anand.webp',
    'restaurantName': 'Gaggan Anand',
    'netflixShowName': 'Chef Table',
    'volume': 2,
    'chapter': 6,
    'city': 'Bangkok',
    'country': 'Tailandia',
    'lat': 13.74080,
    'lng': 100.56758,
    'images': [],
    'address':
        '68 Sukhumvit 31, Khlong Tan Nuea, Watthana, Bangkok 10110, Tailandia',
    'description':
        "With his passions for remaining what traditional Indian food can be, celebrity chef Gaggan Anand created the best restaurant in all of Asia",
    'webPage': 'https://gaggananand.com/',
    'reservationsMail': '',
    'contactPhone': '(+66) 98 883 1022',
    'reservations': 'https://gaggananand.com/request-a-table/',
    'isFavorited': false,
  },
];

List<Map<String, dynamic>> _pizzaRestaurantData = [
  {
    'chefName': 'Chris Bianco',
    'mainImage': 'chris_bianco.jpg',
    'restaurantName': 'Pizzeria Bianco',
    'netflixShowName': 'Chef Table Pizza',
    'volume': 1,
    'chapter': 1,
    'city': 'Phoenix',
    'lat': 33.44995,
    'lng': -112.06551,
    'images': [],
    'address': '623 E Adams St, Phoenix, AZ 85004',
    'country': 'U.S.A',
    'description':
        "An unprecedented approach to ingredients and technique has made Chris Bianco's Phoenix pizzeria the home of what critics deem the best pies in the world",
    'webPage': 'https://www.pizzeriabianco.com/',
    'reservationsMail': '',
    'contactPhone': '',
    'reservations': '',
    'isFavorited': false,
  },
  {
    'chefName': 'Gabriele Bonci',
    'mainImage': 'bonci.jpeg',
    'restaurantName': 'Bonci Pizzarium',
    'netflixShowName': 'Chef Table Pizza',
    'volume': 1,
    'chapter': 2,
    'city': 'Rome',
    'country': 'Italy',
    'lat': 41.90710,
    'lng': 12.44671,
    'images': [],
    'address': 'Via della Meloria, 43, 00136 Roma RM, Italia',
    'description':
        "After revolutionizing the Roman-style slice, Gabrielle Bonci - the Michelangelo of pizza - decided to shed his TV persona and reconnect with the land",
    'webPage': 'https://bonciusa.com/',
    'reservationsMail': '',
    'contactPhone': '',
    'reservations': '',
    'isFavorited': false,
  },
  {
    'chefName': 'Ann Kim',
    'mainImage': 'ann_kim.jpeg',
    'restaurantName': 'Pizzeria Lola',
    'netflixShowName': 'Chef Table Pizza',
    'volume': 1,
    'chapter': 3,
    'city': 'Minneapolis',
    'country': 'U.S.A',
    'lat': 44.90199,
    'lng': -93.31863,
    'images': [],
    'address': '5557 Xerxes Ave S, Minneapolis, MN 55410',
    'description':
        "Ann Kim fought societal barriers and familial expectations to serve kimchi on pizza. Now, she's a James Beard winner with two Minneapolis restaurants.xw",
    'webPage': 'https://www.pizzerialola.com/',
    'reservationsMail': '',
    'contactPhone': '+1 612-424-8338, ext. 3',
    'reservations': '',
    'isFavorited': false,
  },
  {
    'chefName': 'Franco Pepe',
    'mainImage': 'franco_pepe.jpeg',
    'restaurantName': 'Pepe in Grani',
    'netflixShowName': 'Chef Table Pizza',
    'volume': 1,
    'chapter': 4,
    'city': 'Caiazzo',
    'country': 'Italy',
    'lat': 41.17737,
    'lng': 14.36603,
    'images': [],
    'address': 'Vicolo S. Giovanni Battista, 3, 81013 Caiazzo CE',
    'description':
        "In her award-winning Los Angeles restaurant, N/Naka, chef Niki Nakayama brings equal parts creativity, passion and expertise to her kaiseki cuisine.",
    'webPage': 'https://www.pepeingrani.it',
    'reservationsMail': '',
    'contactPhone': '(+1) 310 836 6252',
    'reservations': '',
    'isFavorited': false,
  },
  // {
  //   'chefName': 'Yoshihiro Imai',
  //   'mainImage': 'attica.jpeg',
  //   'restaurantName': 'Attica',
  //   'netflixShowName': 'Chef Table Pizza',
  //   'volume': 1,
  //   'chapter': 5,
  //   'city': 'New Zeland',
  //   'country': 'Australia',
  //   'lat': -37.87689,
  //   'lng': 144.99733,
  //   'images': [],
  //   'address': '74 Glen Eira Rd, Ripponlea VIC 3185, Australia',
  //   'description':
  //       "New Zeland chef Ben Shewry's string connection with nature and dedication to finding new tastes have made his striking restaurant Attica a temple to the art of cooking",
  //   'webPage': '',
  //   'reservationsMail': '',
  //   'contactPhone': '',
  //   'reservations': '',
  //   'isFavorited': false,
  // },
  // {
  //   'chefName': 'Sarah Minnick',
  //   'mainImage': 'alinea.jpeg',
  //   'restaurantName': 'Alinea',
  //   'netflixShowName': 'Chef Table Pizza',
  //   'volume': 1,
  //   'chapter': 6,
  //   'city': 'Chicago',
  //   'country': 'U.S.A.',
  //   'lat': 41.91344,
  //   'lng': -87.64805,
  //   'images': [],
  //   'address': '1723 N Halsted St, Chicago, IL 60614, Estados Unidos',
  //   'description':
  //       "Superstar American chef Grant Achatz has been at the forefront of the molecular gastronomy movement since the 1990s. He wants to vow diners with mistery, emotion and magic just as much as he does with flavor and beauty",
  //   'webPage': '',
  //   'reservationsMail': '',
  //   'contactPhone': '',
  //   'reservations': '',
  //   'isFavorited': false,
  // },
];

class RestaurantService {
  Future<List<Restaurant>> getRestaurants() async {
    final querySnapshot =
        await FirebaseFirestore.instance.collection("restaurantsData").get();
    return querySnapshot.docs
        .map((doc) => Restaurant.fromMap(doc.data()))
        .toList();
  }

  Future<List<Restaurant>> getPizzaRestaurants() async {
    return _pizzaRestaurantData.map((restaurant) {
      return Restaurant.fromMap(restaurant);
    }).toList();
  }

  Future<List<Restaurant>> getAllRestaurants() async {
    final querySnapshot =
        await FirebaseFirestore.instance.collection("restaurantsData").get();
    return querySnapshot.docs
        .map((doc) => Restaurant.fromMap(doc.data()))
        .toList();
  }
}
